# Generated by Django 4.1.3 on 2022-12-15 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_informations_bio_alter_informations_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
