# Generated by Django 4.1.3 on 2022-12-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_informations_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
