# Generated by Django 4.1.3 on 2022-12-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_thread_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
