# Generated by Django 4.1.3 on 2022-12-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_thread_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='origin',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
