# Generated by Django 4.1.4 on 2022-12-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_informations_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='photo',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
