# Generated by Django 4.1.4 on 2022-12-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_post_likedby_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likedby',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
