# Generated by Django 4.1.4 on 2022-12-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_remove_post_likedby_remove_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
