# Generated by Django 4.1.4 on 2022-12-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_alter_thread_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
