# Generated by Django 4.1.4 on 2022-12-23 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_alter_informations_image_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='who',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='forum.informations'),
            preserve_default=False,
        ),
    ]
